### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [rcmdnk/rcmdnk.github.io#3]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`index.html`](https://github.com/rcmdnk/rcmdnk.github.io/blob/e4254fb66dfe47b2ca83f59bea80a9e975dd670e/blog/page/44/index.html). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by rcmdnk** [comment]
Thanks for the information.

I updated these links to `https://formulae.brew.sh/cask/` in my blog posts.
